name: ci-regressions
run-name: Run CI Regressions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  regressions:
    name: CI Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Grab Tox and Poetry
        run: pip install tox poetry

      - name: Lint and Test
        run: tox
        env:
          MARKETSTACK_TOKEN_TEST: "${{ secrets.MARKETSTACK_TOKEN_TEST }}"

      - name: Run a Build
        run: poetry build

      - name: Create a build-artifacts tarball
        run: |
          tar -czf \
            build-artifacts.tar.gz \
            test-artifacts-* \
            dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts.tar.gz
          path: build-artifacts.tar.gz
